/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _terminusIBM_h_
#define _terminusIBM_h_
//---------------------------------------------------------------------------------
extern const unsigned char terminusIBM[];
extern const int terminusIBM_size;
//---------------------------------------------------------------------------------
#endif //_terminusIBM_h_
//---------------------------------------------------------------------------------
